services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mini-project-db
    environment:
      MSSQL_SA_PASSWORD: "Password#123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1435:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - projectnet

  dbtool:
    image: mcr.microsoft.com/mssql-tools:latest
    networks:
      - projectnet

volumes:
  mssql-data:
networks:
  projectnet:
