// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace webtimesheet.Models;

public partial class TimesheetsDbContext : DbContext
{
    public TimesheetsDbContext(DbContextOptions<TimesheetsDbContext> options)
        : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("Server=127.0.0.1,1435;Database=TimesheetsDb;uid=sa;pwd=Password#123;TrustServerCertificate=True;");
    }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Timesheet> Timesheets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Timesheet>(entity =>
        {
            entity.ToTable(tb => tb.HasTrigger("trg_Timesheets_Update"));
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}