// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace webtimesheet.Models;

public partial class Timesheet
{
    [Key]
    [Column("TimesheetID")]
    public int TimesheetId { get; set; }

    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal HoursWorked { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }
    public Timesheet TimesheetsNavigation { get;  set; }
}